default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: postgres
  password:

development:
  <<: *default
  database: db_saver_development
  host: localhost

test:
  <<: *default
  database: db_saver_test
