# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150105133259) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "tasks", id: false, force: true do |t|
    t.text "New_Contact_Work_Phone__c"
    t.text "ActivityDate"
    t.text "New_Contact_Country__c"
    t.text "Mail_Stop_End_Date__c"
    t.text "IsArchived"
    t.text "CreatedById"
    t.text "Customer_Experience__c"
    t.text "DCB_48hr_Compliance__c"
    t.text "Feedback__c"
    t.text "Preferred_Call_Time__c"
    t.text "FailedCall__c"
    t.text "IsDeleted"
    t.text "Preferred_Dealer_Change_Reason__c"
    t.text "RecordTypeId"
    t.text "Home_Sequence__c"
    t.text "RecurrenceInterval"
    t.text "SystemModstamp"
    t.text "Country__c"
    t.text "Action_Type__c"
    t.text "PMG_Type__c"
    t.text "New_Contact_Home_Phone__c"
    t.text "DCB_24hr_Compliance__c"
    t.text "CampaignName__c"
    t.text "Temp_Away_End_Date__c"
    t.text "Email_Consent__c"
    t.text "Email__c"
    t.text "Phone_Consent__c"
    t.text "CreatedDate"
    t.text "Mobile_Phone__c"
    t.text "OwnerId"
    t.text "RecurrenceType"
    t.text "Contact_Changed__c"
    t.text "Email_Type_2__c"
    t.text "New_Contact_First_Name__c"
    t.text "Work_Phone_Extension__c"
    t.text "SLA_Complete__c"
    t.text "WhatId"
    t.text "LastModifiedById"
    t.text "RecurrenceDayOfMonth"
    t.text "Mobile_Phone_Consent__c"
    t.text "DialedNumber__c"
    t.text "Subject"
    t.text "RecurrenceDayOfWeekMask"
    t.text "New_Contact_City__c"
    t.text "Work_Sequence__c"
    t.text "Dialer_Disposition__c"
    t.text "Language__c"
    t.text "New_Contact_Address__c"
    t.text "Completed_Date__c"
    t.text "Middle_Name__c"
    t.text "Phone__c"
    t.text "Call_Back_Daytime_Indicator__c"
    t.text "WhoId"
    t.text "Postal_Code__c"
    t.text "RecurrenceStartDateOnly"
    t.text "Odometer_Units__c"
    t.text "CallDurationInSeconds"
    t.text "New_Contact_Address_Line_2__c"
    t.text "RecurrenceTimeZoneSidKey"
    t.text "Work_Phone__c"
    t.text "TMS_Disposition__c"
    t.text "CallDisposition"
    t.text "New_Contact_Last_Name__c"
    t.text "Service_Marketing_Call_ID__c"
    t.text "Service_Marketing_Call_Type__c"
    t.text "Call_Centre_Id__c"
    t.text "Comment_Audience__c"
    t.text "SLA_Compliance__c"
    t.text "Mobile_Sequence__c"
    t.text "Odometer_Reading__c"
    t.text "Call_Start_Time__c"
    t.text "Question_1__c"
    t.text "IsVisibleInSelfService"
    t.text "X24hr_Due_Date_Time__c"
    t.text "Preferred_Mail_Type__c"
    t.text "New_Contact_Zip__c"
    t.text "Work_Phone_Consent__c"
    t.text "Preferred_Phone_Type__c"
    t.text "Type"
    t.text "Mail_Stop_Start_Date__c"
    t.text "CallDisposition__c"
    t.text "Description"
    t.text "Priority"
    t.text "CallObject"
    t.text "Action_Taken__c"
    t.text "Request_Date__c"
    t.text "Send_Email_Request_Indicator__c"
    t.text "Work_Email_Consent__c"
    t.text "Agent_ID__c"
    t.text "ReminderDateTime"
    t.text "Salutation__c"
    t.text "Status"
    t.text "Last_Name__c"
    t.text "RecurrenceEndDateOnly"
    t.text "Work_Email__c"
    t.text "First_Name__c"
    t.text "Contact_Origin__c"
    t.text "New_Contact_Home_Ext__c"
    t.text "Question_2__c"
    t.text "X48hr_Due_Date_Time__c"
    t.text "DNIS__c"
    t.text "IsRecurrence"
    t.text "Satisfaction__c"
    t.text "IsClosed"
    t.text "Email_Type_1__c"
    t.text "Request_Time__c"
    t.text "Call_Back_Time__c"
    t.text "Created_By_Role__c"
    t.text "Deceased__c"
    t.text "LastModifiedDate"
    t.text "Call_End_Time__c"
    t.text "IsReminderSet"
    t.text "Id"
    t.text "State__c"
    t.text "Street__c"
    t.text "LETTER_ATTACHED__c"
    t.text "Call_Back_Phone__c"
    t.text "New_Contact_State__c"
    t.text "New_Contact_Work_Ext__c"
    t.text "AccountId"
    t.text "Dealer_Code__c"
    t.text "Service_Description__c"
    t.text "CustomerID__c"
    t.text "CallType"
    t.text "RecurrenceActivityId"
    t.text "ANI__c"
    t.text "Temp_Away_Start_Date__c"
    t.text "Call_Phone__c"
    t.text "RecurrenceMonthOfYear"
    t.text "RecurrenceInstance"
    t.text "Phone_Extension__c"
    t.text "Call_Recording_ID__c"
    t.text "City__c"
    t.text "Preferred_Dealer_Change__c"
    t.text "Department__c"
  end

end
