class CreateCases < ActiveRecord::Migration
  def change
    create_table :cases, id: false do |t|
      t.text :Survey_NPS_Score_1__c
      t.text :Backorder_Type_3__c
      t.text :Lead_Comments_Long__c
      t.text :Contracted_Monthly_Payment__c
      t.text :Frequency_of_Problem__c
      t.text :Issue_Details__c
      t.text :Do_Not_Contact__c
      t.text :IIR_Date__c
      t.text :Section__c
      t.text :Technical_Escalation_Status__c
      t.text :SurveyScore__c
      t.text :Language_Code__c
      t.text :Is_Customer_Satisfied__c
      t.text :ln__c
      t.text :VPP_On_Site_Activation_Interest__c
      t.text :Intended_Promotions__c
      t.text :Letter_Sent_Date__c
      t.text :SIC__c
      t.text :Quantity_5__c
      t.text :Lease_Start_Date__c
      t.text :DRT_Support_IIR_Status__c
      t.text :Disablement_Zip__c
      t.text :Executive_Referral__c
      t.text :Backorder_Ranking_5__c
      t.text :TSO_Number__c
      t.text :Tested_By__c
      t.text :Considered_Vehicle_Data__c
      t.text :Supply_ETD__c
      t.text :Customer_Conversation_Notes__c
      t.text :Mailing_City__c
      t.text :How_were_we_contacted__c
      t.text :Recommendation_Rating__c
      t.text :Symptom_Code_Category__c
      t.text :Contract_Start_Date__c
      t.text :Spanish_Speaking_Customer__c
      t.text :Subscription_Status__c
      t.text :Beyond_Basic_Warranty_Months__c
      t.text :Vehicle_Purchased__c
      t.text :Order_Number_2__c
      t.text :Backorder_Ranking_1__c
      t.text :Last_Contact_Date__c
      t.text :Survey_Dealer_Number__c
      t.text :Part_Description_1__c
      t.text :Dealer__c
      t.text :With_Customer_With_Dealer__c
      t.text :Special_Remark_Line_Count__c
      t.text :Case_Reason_Other__c
      t.text :Match__c
      t.text :Call_Start_Time__c
      t.text :DTS_User_Cell_Phone__c
      t.text :ICCID__c
      t.text :NMAC_Account__c
      t.text :is1__IS_Account_ID__c
      t.text :Trade_In_Value__c
      t.text :App_Version__c
      t.text :Fire_Indicator__c
      t.text :Description
      t.text :Priority
      t.text :Head_Unit__c
      t.text :Middle_Initial__c
      t.text :VCAN__c
      t.text :First_Call_Resolution__c
      t.text :Loan_Months_Remaining__c
      t.text :Short_Description__c
      t.text :Attachment_Indicator__c
      t.text :First_Name__c
      t.text :Incident_Number__c
      t.text :RDR_Account__c
      t.text :Reason_assigned_to_Inf_of_Manhattan__c
      t.text :Case_Age__c
      t.text :Incident_RO_Date__c
      t.text :FirstCallResolution__c
      t.text :Reopen_New_Count__c
      t.text :Model_Id__c
      t.text :Survey_NPS_Score_3__c
      t.text :Preferred_Timeslot__c
      t.text :Agent_Reason__c
      t.text :LastReferencedDate
      t.text :NNA_Net_Hot_Alert_Type__c
      t.text :Lead_Provider_Detail__c
      t.text :Resend_Request_Indicator__c
      t.text :IIR__c
      t.text :X24_hour_Response_Date__c
      t.text :Nearest_Infiniti_Dealer__c
      t.text :Goodwill_Offered_Date__c
      t.text :Who_contacted_us__c
      t.text :Escalation_Type_ID__c
      t.text :Symptom_Code__c
      t.text :Survey_ID__c
      t.text :Executive_Summary_Completed_Date__c
      t.text :BeyondBasicWarrantyMonths__c
      t.text :Caller_Reference_No__c
      t.text :Preferred_Appointment_Time__c
      t.text :Symptom_Code_Issue__c
      t.text :Confirmed_Appointment_Date__c
      t.text :Reason
      t.text :Follow_Up_Request__c
      t.text :Escalated_to_SSQ__c
      t.text :Literature_Data__c
      t.text :IsClosedOnCreate
      t.text :Vehicle_Service_Contract__c
      t.text :Li_Community_User__c
      t.text :Part_Description_3__c
      t.text :Query_Escalated_To__c
      t.text :Tow_Mileage__c
      t.text :Phone_TMID__c
      t.text :DTS_Name__c
      t.text :Customer_Interested_in__c
      t.text :Location_Name__c
      t.text :HasCommentsUnreadByOwner
      t.text :Phone_Number__c
      t.text :FF_Score__c
      t.text :Assignment_Level_Code__c
      t.text :Lead_Category__c
      t.text :SlaExitDate
      t.text :LastViewedDate
      t.text :Goodwill_Offered__c
      t.text :Notification_2__c
      t.text :When_Plan_Purchase__c
      t.text :Callback_Required__c
      t.text :Problem_Resolved__c
      t.text :Most_Recent_Service_Date__c
      t.text :Open_Promotion__c
      t.text :Payment_Offer_Clean__c
      t.text :Board_ID__c
      t.text :Vehicle_Purchased_Miles__c
      t.text :Call_Back_Required__c
      t.text :Preferred_Contact_Method__c
      t.text :Number_Injured__c
      t.text :ROM__c
      t.text :Service_Provider_ID__c
      t.text :Month_Mailed__c
      t.text :Parts_Manager_Notified__c
      t.text :Executive_Summary__c
      t.text :Mileage_Allowance__c
      t.text :RCAS_Active__c
      t.text :Hot_Alerts_indicator__c
      t.text :How_was_the_action_taken__c
      t.text :Date_Observed__c
      t.text :Service_Contract__c
      t.text :DealerExternalId__c
      t.text :SurveyGizmo24HourSent__c
      t.text :Will_Client_Fund__c
      t.text :VSC_Mailing_Street__c
      t.text :Road_Service_Call_Number__c
      t.text :Injury_Date__c
      t.text :Control_Group_Check_Box__c
      t.text :Sales_Type__c
      t.text :DRT_Support_Status__c
      t.text :Incident_Date__c
      t.text :Beyond_Basic_Warranty_Miles__c
      t.text :X24_hour_Reponse_Date__c
      t.text :Reopened_Times__c
      t.text :Type
      t.text :Quantity_2__c
      t.text :DTC_2__c
      t.text :Email2__c
      t.text :CreatedBy__c
      t.text :Control_Number__c
      t.text :Reported_From__c
      t.text :Severity_Rating_Code__c
      t.text :Part_Number_4__c
      t.text :Action_Code__c
      t.text :Destination_Type__c
      t.text :WhatIsTheIssue2__c
      t.text :CustomerNameFormula__c
      t.text :TSS_Name__c
      t.text :Survey_NPS__c
      t.text :Website__c
      t.text :Product_Alert_Number__c
      t.text :Mailing_Zip_Plus4__c
      t.text :SparkID__c
      t.text :DTC_3__c
      t.text :Responsible_Dealer_Number__c
      t.text :Dealer_Referral_Code__c
      t.text :Current_Mileage__c
      t.text :Hot_Alert_Cost__c
      t.text :Maritz_Customer_Id__c
      t.text :Verified__c
      t.text :RequestedDealerActionIsBlank__c
      t.text :Hot_Alert_Source__c
      t.text :Requested_By__c
      t.text :Phone_Manufacturer__c
      t.text :Preferred_Dealer__c
      t.text :RHR_Start_Date__c
      t.text :CaseServicingDealerStatus__c
      t.text :Date_Email_Responded__c
      t.text :Survey_Response_Date__c
      t.text :Document_ID__c
      t.text :Dealer_Update_By_User_ID__c
      t.text :Manager_Reviewed_Indicator__c
      t.text :Email_Do_Not_Email__c
      t.text :Production_Release_Date__c
      t.text :Settlements_Open__c
      t.text :CongaTestLink__c
      t.text :ModelSeriesFromVehicle__c
      t.text :Case_Servicing_Dealer_Code__c
      t.text :Order_Number__c
      t.text :Component_Group__c
      t.text :Reservation_Number__c
      t.text :Severity__c
      t.text :Solution_Rating__c
      t.text :Order_Number_5__c
      t.text :OtherInfo__c
      t.text :Vehicle_DQR_Information__c
      t.text :Calculated_Days_Down__c
      t.text :Dealer_CA_Manager_Name__c
      t.text :ProductId
      t.text :RecordTypeId
      t.text :Spare_8__c
      t.text :Remove_Dealer_Sharing__c
      t.text :Reason_for_Call_Code__c
      t.text :Survey_Index_Score__c
      t.text :Make__c
      t.text :Specialist_Code_UP__c
      t.text :Remediation_Plan__c
      t.text :Survey_Days__c
      t.text :DTS_User_Office_Phone__c
      t.text :Model_Year__c
      t.text :Revision_Number__c
      t.text :What_Department__c
      t.text :Social_Status__c
      t.text :NC_Subscription_Status__c
      t.text :VIN__c
      t.text :Thread_ID__c
      t.text :Datanet_Dealer_Indicator__c
      t.text :QA_Release_Date__c
      t.text :Vehicle_Mileage_Prior_Value__c
      t.text :Contact_Type1__c
      t.text :Component_Code_Issue__c
      t.text :IsEscalated
      t.text :CheckRequestsSubmitted__c
      t.text :FFFS_Date__c
      t.text :User_Defined_Text_1__c
      t.text :Part_Description_2__c
      t.text :Fire_Date__c
      t.text :Catalog_Update_Responsibility__c
      t.text :Escalation_Elapsed_Days__c
      t.text :Accident_Indicator__c
      t.text :Additional_Days_Down__c
      t.text :Root_Cause_Code__c
      t.text :Region_d__c
      t.text :Home_Phone_Do_Not_Call__c
      t.text :Survey_Verbatim_2__c
      t.text :Customer_ID__c
      t.text :Notification_4__c
      t.text :Action_Flag__c
      t.text :Lease_or_Loan__c
      t.text :VPP_Promotion_Opt_In__c
      t.text :TREAD_Effective_Date__c
      t.text :Catalog_Update_Rqrd__c
      t.text :Responsibility_Code__c
      t.text :User_Defined_Text_3__c
      t.text :Dealer_Country__c
      t.text :Letter_Received_Date__c
      t.text :Case_Type__c
      t.text :Alternate_Email__c
      t.text :Goodwill_Processed__c
      t.text :Backorder_Type_2__c
      t.text :CA_Multiple_Repairs__c
      t.text :Co_Leasee_Co_Buyer_First_Name__c
      t.text :Tow_To_State__c
      t.text :LastModifiedDate
      t.text :New_User_Email_Address__c
      t.text :Vehicle_In_Service_Date__c
      t.text :Datanet_Dealer_Count__c
      t.text :Error_Reproduced__c
      t.text :SSQSurvey_Response_Date__c
      t.text :Lead_Provider_Name__c
      t.text :Service_Provider_ETA__c
      t.text :Rollover_Indicator__c
      t.text :Order_Number_1__c
      t.text :Previous_Repair_Location__c
      t.text :Case_Owner_Email__c
      t.text :Problem_Analysis__c
      t.text :SuppliedName
      t.text :Reopen_Date__c
      t.text :Reopen_Callback_Date__c
      t.text :Escalation_Resolved__c
      t.text :Production_Date__c
      t.text :Retail_Dealer__c
      t.text :Reason__c
      t.text :Secondary_Reason__c
      t.text :Region_Code__c
      t.text :Issue_Type__c
      t.text :CreatedById
      t.text :Purchase_Timeframe__c
      t.text :Originator_Code__c
      t.text :Other_Concern__c
      t.text :VPP_Contact_Phone__c
      t.text :Area_Impacted__c
      t.text :Part_Number_5__c
      t.text :Contract_Type__c
      t.text :Responsible_District__c
      t.text :NNAnet_Status_at_Start__c
      t.text :CreatedDate
      t.text :Social_Resolution__c
      t.text :VPP_Contact_Title__c
      t.text :IsStopped
      t.text :Requested_RO_Number__c
      t.text :Shared_via_Portal__c
      t.text :DTS_User_Email__c
      t.text :Survey__c
      t.text :Other_TECH_LINE_Reports__c
      t.text :Mobile_Phone_Do_Not_Call__c
      t.text :Social_Support_Involvement__c
      t.text :VPP_Contact_First__c
      t.text :Escalation_Resolved_By__c
      t.text :Email_Closed_Loop_Verbatim__c
      t.text :Pre_Ordered__c
      t.text :Responsible_Region__c
      t.text :Field_Inspection_Indicator__c
      t.text :SuppliedEmail
      t.text :Call_Center__c
      t.text :Contact_Type2_C__c
      t.text :RHR_Completed_Date__c
      t.text :Lead_Provider__c
      t.text :Component_Code__c
      t.text :Assignee_1__c
      t.text :Specialist_Code__c
      t.text :What_is_the_issue__c
      t.text :Caller_Name__c
      t.text :Featured_Vehicle__c
      t.text :Survey_NPS_Type_2__c
      t.text :Loan_Maturity_Date__c
      t.text :Phone_Carrier__c
      t.text :Comment_Text3__c
      t.text :Special_Root_Cause_Closing_Code__c
      t.text :Hot_Alert_Status__c
      t.text :Requesting_Department__c
      t.text :VehiclePurchasedType__c
      t.text :Report_Type__c
      t.text :TSS_Code_Primary__c
      t.text :Quantity_4__c
      t.text :CST_Approvals__c
      t.text :Tow_To_Zip__c
      t.text :How_Did_you_Find_the_Answer__c
      t.text :LeadProviderNameTranslated__c
      t.text :Bill_Group__c
      t.text :Special_Root_Cause_Closing_Code_2__c
      t.text :Reopen_Other_Date__c
      t.text :Originator_Region__c
      t.text :Vehicle_Maintained_Location__c
      t.text :Current_Vehicle_Lease_Exp_Date__c
      t.text :DealerCode__c
      t.text :Mileage_Initial__c
      t.text :Status
      t.text :BeyondBasicWarrantyMiles__c
      t.text :Check_Request_Origin__c
      t.text :Current_Vehicle_Lease_Indicator__c
      t.text :DQR_Number__c
      t.text :TCU__c
      t.text :Hot_Alert_Date__c
      t.text :Backorder_Type_5__c
      t.text :Part_Description_4__c
      t.text :Handled__c
      t.text :Alternate_Email_Do_Not_Email__c
      t.text :Lease_Months_Remaining__c
      t.text :IsClosed
      t.text :First_Response__c
      t.text :Country_Origin__c
      t.text :Follow_Up_Preference__c
      t.text :FOM_Notified__c
      t.text :Total_Verbatims__c
      t.text :Servicing_Dealer__c
      t.text :Distributor_Code__c
      t.text :Dealer_Address_Phone_Number_and_Fax__c
      t.text :FFFS__c
      t.text :Spare_9__c
      t.text :Escalation_Ticket__c
      t.text :Stage_Status__c
      t.text :SuppliedCompany
      t.text :Inquiry_Type__c
      t.text :Community_URL__c
      t.text :Other_Information__c
      t.text :Assignee_2__c
      t.text :VSC_Requests__c
      t.text :Assignment_Level__c
      t.text :Legacy_Case_Number__c
      t.text :Incoming_Car_Indicator__c
      t.text :Lease_Maturity_Date__c
      t.text :Segment_Letter__c
      t.text :Previous_Repair_Date__c
      t.text :Disablement_City__c
      t.text :fn__c
      t.text :Key_Part_Code__c
      t.text :Completed_Outbound_Calls__c
      t.text :Record_Number__c
      t.text :Reopen_New_Date__c
      t.text :Agent_Login__c
      t.text :Brakes__c
      t.text :Dealer_Reference_Number__c
      t.text :Tow_To_City__c
      t.text :Case_ReasonTemplate__c
      t.text :Dealer_Resolved__c
      t.text :Customer_Name__c
      t.text :Service_Dealer_Number__c
      t.text :Author_Rank__c
      t.text :Repair_Attempts__c
      t.text :ClosedDate
      t.text :Days_Closed__c
      t.text :Callback_Count__c
      t.text :ContactId
      t.text :Model_of_Interest_1st__c
      t.text :New_Preferred_Dealer__c
      t.text :Retailer_Close_Date__c
      t.text :IsDeleted
      t.text :Segment_Mailed__c
      t.text :VPP_Contact_Email__c
      t.text :Notification_1__c
      t.text :Payment_Request_Identifier__c
      t.text :Dealer_PDC__c
      t.text :Call_Resolution__c
      t.text :Part_Description_5__c
      t.text :CA_CaseReopenCount__c
      t.text :NNA_Field_Inspection_Date__c
      t.text :Area__c
      t.text :Quantity_1__c
      t.text :Hours_Worked__c
      t.text :Response_Date__c
      t.text :Critical_Status_Flag__c
      t.text :Comment_Text1__c
      t.text :LastModifiedById
      t.text :Lease_Monthly_Payment__c
      t.text :Date_Sent__c
      t.text :Callback_Date_CYMD__c
      t.text :Number_of_Employees__c
      t.text :Escalated_User__c
      t.text :Channel__c
      t.text :FSSS__c
      t.text :Incident_Category__c
      t.text :Backorder_Ranking_4__c
      t.text :SurveyGizmoLeadCreationtime__c
      t.text :New_User_First_Name__c
      t.text :Mailing_Street_2__c
      t.text :Customer_Satisfied_With_Dealer__c
      t.text :Dealer_Region_Code_Form__c
      t.text :Customer_Comments__c
      t.text :Property_Damage_Date__c
      t.text :SurveyGizmoSendStatus__c
      t.text :Event_Date__c
      t.text :IPA_Subscription_Status__c
      t.text :Order_Number_3__c
      t.text :VCS_Validation__c
      t.text :Dealer_Update_Date__c
      t.text :Suggested_Hours_Worked__c
      t.text :Transferred_to_RCAS__c
      t.text :Firmware_Version__c
      t.text :Previous_Promotion_Other__c
      t.text :Location_Employees__c
      t.text :Previous_Promotions__c
      t.text :Surveyable__c
      t.text :Mailing_Street__c
      t.text :Catalog_Pub__c
      t.text :Responsible_Dealer_Data__c
      t.text :Company_Name__c
      t.text :Supervisor_Review__c
      t.text :Operating_Temperature__c
      t.text :F_I_Manager_Service_Tech__c
      t.text :X24_hour_Response__c
      t.text :Customer_Declined__c
      t.text :Author_Login__c
      t.text :VSC_Mailing_City__c
      t.text :Inspection_Time_Notes__c
      t.text :Expected_Response_Date__c
      t.text :Hot_Alert_Age__c
      t.text :Callback_UserID__c
      t.text :Tow_To_Address_Name__c
      t.text :Survey_Type__c
      t.text :Model_Line__c
      t.text :Dealer_Quotes_Request__c
      t.text :Follow_Up_NPS_Type__c
      t.text :Registered__c
      t.text :Case_Owner_Location2__c
      t.text :Requested_Part__c
      t.text :Sales_Service_Consultant__c
      t.text :Requested_Dealer_Call__c
      t.text :User_Defined_Number_1__c
      t.text :VSC_Mailing_State__c
      t.text :Lead_Comments__c
      t.text :Escalation_ID__c
      t.text :SIM__c
      t.text :Datanet_Dealer_Date__c
      t.text :Branded_Title__c
      t.text :Backorder_Ranking_3__c
      t.text :EscalatedByID__c
      t.text :DOM_Notified__c
      t.text :SuppliedPhone
      t.text :Phone_Operating_System__c
      t.text :Disposition__c
      t.text :Comment_Text__c
      t.text :Shared_With__c
      t.text :Email_Indicator__c
      t.text :Deflection_Risk__c
      t.text :Region__c
      t.text :Legacy_Owner_Id__c
      t.text :Approved_Phone__c
      t.text :Sentiment_Band__c
      t.text :FollowUpTimeframe__c
      t.text :Considered_Vehicle_Model__c
      t.text :Tow_To_Address__c
      t.text :Part_Number_2__c
      t.text :Dealer_Action_Plan__c
      t.text :DocumentID__c
      t.text :Campaign_Type__c
      t.text :Disablement_Reason__c
      t.text :TREAD_Component_Prior_Value__c
      t.text :Decile_Score__c
      t.text :Community_ID__c
      t.text :New_User_Last_Name__c
      t.text :NNA_Notes__c
      t.text :Submitted_Check_Requests__c
      t.text :Who_called__c
      t.text :OwnerId
      t.text :District_Name__c
      t.text :Channel_Designation_Code__c
      t.text :Browser_Version__c
      t.text :No_Phone_Numbers__c
      t.text :PNC_Description__c
      t.text :AssetId
      t.text :Message_Posted__c
      t.text :Buyback__c
      t.text :Disqualified_Reason__c
      t.text :CDIID__c
      t.text :Subject
      t.text :Unintended_Acceleration__c
      t.text :Disablement_Street__c
      t.text :Buyback_Restriction__c
      t.text :Tech_Preferred_Phone__c
      t.text :Contact_Record_Type__c
      t.text :Legacy_Root_Cause__c
      t.text :Vehicles_Owned__c
      t.text :Defect__c
      t.text :IIR_Indicator__c
      t.text :BeyondPTWarrantyMiles__c
      t.text :Case_External_ID__c
      t.text :Tech_Phone_Type__c
      t.text :Loan_Payoff_Amount__c
      t.text :Where_did_this_originate__c
      t.text :EntitlementId
      t.text :Vehicle_Model__c
      t.text :Response_Time__c
      t.text :VSC_Reprint_Request__c
      t.text :Manufacturer_Date__c
      t.text :URL_Related_to_Issue__c
      t.text :Backorder_Type_4__c
      t.text :Supply_Resolution__c
      t.text :ROI__c
      t.text :Contract_Term__c
      t.text :Home_Phone__c
      t.text :User_Defined_Date_1__c
      t.text :Dealer_Instructions__c
      t.text :Infiniti_Action_History__c
      t.text :Issue_Categories__c
      t.text :Escalation_Started__c
      t.text :Email_Closed_Loop_Date__c
      t.text :Co_Leasee_Co_Buyer_Last_Name__c
      t.text :Work_Phone_Do_Not_Call__c
      t.text :Date_Closed__c
      t.text :Email_Reminder_Sent__c
      t.text :Considered_Vehicle_Make__c
      t.text :Multiple_Repairs__c
      t.text :Phone_Model__c
      t.text :Contacted_by_Dealer__c
      t.text :Disablement_State__c
      t.text :Model1__c
      t.text :Pre_Approval_Amount__c
      t.text :Publication_Date__c
      t.text :Receipt_Date_ID__c
      t.text :Who_Took_Action__c
      t.text :Client_Dealer_ID__c
      t.text :Calls_Complete__c
      t.text :No_Response_Required__c
      t.text :Total_Days_Down__c
      t.text :Contact_ID__c
      t.text :Origination__c
      t.text :Trade_In_Rough__c
      t.text :CSM_Notified__c
      t.text :Business_Unit__c
      t.text :Dealer_Name__c
      t.text :In_Service_Date__c
      t.text :Country_of_Origin__c
      t.text :Engine_Number__c
      t.text :Owner_Portal_ID_User_ID__c
      t.text :VPP_Contact_Last__c
      t.text :Field_Open_Date__c
      t.text :Repair_Root_Cause_Code__c
      t.text :Id
      t.text :Sent_to_Legal_Indicator__c
      t.text :Ambient_Humidity__c
      t.text :ContactHomePhone__c
      t.text :Reopen_New_UserID__c
      t.text :Call_Disposition_Code__c
      t.text :Dealer_Code__c
      t.text :Lease_Payoff_Amount__c
      t.text :Agent_Comments__c
      t.text :Tel_Survey_Indicator__c
      t.text :Reason_for_Call_Description__c
      t.text :Technical_Escalation_Resolution_Notes__c
      t.text :Model_of_Interest_2nd__c
      t.text :BeyondPTWarrantyMonths__c
      t.text :Ambient_Temperature__c
      t.text :Trans_Type__c
      t.text :Sequence_Number__c
      t.text :Engine_Code_8__c
      t.text :Reason_For_Call__c
      t.text :Third_Party_Involvement__c
      t.text :Classification__c
      t.text :Survey_NPS_Score_2__c
      t.text :Categorizations__c
      t.text :EveningPhone__c
      t.text :DTS_Notification__c
      t.text :Servicing_Dealer_Region__c
      t.text :Other_DTCs__c
      t.text :Transaction_Master_Id__c
      t.text :SlaStartDate
      t.text :IsDOM__c
      t.text :Mailing_Zip_Code__c
      t.text :SystemModstamp
      t.text :Part_Number_1__c
      t.text :Email_Received_Date__c
      t.text :Form__c
      t.text :Survey_NPS_Type_1__c
      t.text :IsSelfServiceClosed
      t.text :Legacy_Root_Cause_2__c
      t.text :Survey_Source__c
      t.text :Mobile_Phone__c
      t.text :CongaLastPrint__c
      t.text :Time_Observed__c
      t.text :Confirmed_Appointment_Time__c
      t.text :DaysDownManual__c
      t.text :Closed_by_NMAC__c
      t.text :Assignment_Level_Name__c
      t.text :Bonus_Cash_Code__c
      t.text :Safety_Indicator__c
      t.text :Diagnostic_Questions__c
      t.text :Elapsed_Time__c
      t.text :Date_Email_Received__c
      t.text :Notification_3__c
      t.text :AlternatePhone__c
      t.text :PrintCasesConga__c
      t.text :Supply_Status__c
      t.text :Work_Phone__c
      t.text :Net_Promoter_Score__c
      t.text :DealerRegion_Code__c
      t.text :Survey_Request_Date__c
      t.text :Property_Damage_Indicator__c
      t.text :Parts_Dept_Fax__c
      t.text :SurveyGizmoSurveySent__c
      t.text :Overall_Customer_Satisfaction__c
      t.text :SurveyGizmoBatchdatetime__c
      t.text :is1__Chat_ID__c
      t.text :Service_Provider_Name__c
      t.text :Engine_Code_4__c
      t.text :Likely_To_Purchase__c
      t.text :Dealer_Days__c
      t.text :Primary_Reason__c
      t.text :Text_Okay__c
      t.text :Owner_ZCA_ID__c
      t.text :Revision_Date__c
      t.text :Trade_In_Average__c
      t.text :Tracking__c
      t.text :Beyond_PT_Warranty_Months__c
      t.text :Other_Primary_Reason_for_Call__c
      t.text :Survey_Specific_Contact_Information__c
      t.text :Task_ID__c
      t.text :Quantity_3__c
      t.text :Selected_Dealer_Number__c
      t.text :Root_Cause_Code_2__c
      t.text :Reopen_Other_UserID__c
      t.text :Committed_Promotion_Other__c
      t.text :Last_Name__c
      t.text :Yesmail_Inquiry__c
      t.text :Bluetooth_Ticket_Status__c
      t.text :Exec_Received_Date__c
      t.text :NNAnetStatus_at_Start__c
      t.text :Reopen_Callback_UserID__c
      t.text :Mail_Stop__c
      t.text :Buyback_Status__c
      t.text :Incident_Category_Name__c
      t.text :Post_Follow_Up_NPS_Score__c
      t.text :Rollover_Date__c
      t.text :Where_did_this_originate_2__c
      t.text :Steering__c
      t.text :Comment_Text2__c
      t.text :Service_Manager_Notified__c
      t.text :StopStartDate
      t.text :Reopen_Callback_Count__c
      t.text :Call_End_Time__c
      t.text :Lease_Term__c
      t.text :Responsible_PDC__c
      t.text :Purchase_Date__c
      t.text :Preferred_Appointment_Date__c
      t.text :AccountId
      t.text :Escalate_To__c
      t.text :Time_to_ResolveSocial__c
      t.text :User_Defined_Text_2__c
      t.text :Total_Calls_Open_and_Closed__c
      t.text :Alert_Trigger_Verbatim__c
      t.text :Lease_Loan_Maturity_Days__c
      t.text :TREAD_Component__c
      t.text :Dealer_Case_Request__c
      t.text :InterviewID__c
      t.text :Part_Number_3__c
      t.text :Project_Number__c
      t.text :Check_Requests_Total__c
      t.text :IC_Subscription_Status__c
      t.text :X24_hour_Reponse__c
      t.text :ParentId
      t.text :Managed_Services_Scope__c
      t.text :Closed_by_Suppression__c
      t.text :Backorder_Type_1__c
      t.text :DTC_1__c
      t.text :Op_Subscription_Status__c
      t.text :Previous_Issue__c
      t.text :Record_Suffix__c
      t.text :Customer_Satisifed_With_Brand__c
      t.text :Time_Logged__c
      t.text :SRS__c
      t.text :Supporting_Documents__c
      t.text :Mailing_State__c
      t.text :Follow_Up_Date__c
      t.text :Trade_In_Clean__c
      t.text :Color_Code__c
      t.text :Case_Age_Days__c
      t.text :Tech_Preferred_Email__c
      t.text :Specialist_Code_Uppercase__c
      t.text :RCAS_ID__c
      t.text :Requested_Part_Number__c
      t.text :AssignmentLevel__c
      t.text :Equity__c
      t.text :Pre_Approval_Number__c
      t.text :VPP_Claim_Code__c
      t.text :TCU_Activation_Status__c
      t.text :SurveyGIzmoBatchSendDateTime__c
      t.text :Road_Service_Call_Indicator__c
      t.text :Customer_Disposition_After__c
      t.text :Sales_Manager_Notified__c
      t.text :Response_Type__c
      t.text :Customer_Escalated__c
      t.text :Service_Provided__c
      t.text :Model_Line_Series__c
      t.text :Rating__c
      t.text :Techline_Notifications_Sent__c
      t.text :SpaceID__c
      t.text :Current_APR__c
      t.text :Operating_Mode__c
      t.text :DRT_Origination__c
      t.text :Data_Net__c
      t.text :CSI_SSI__c
      t.text :LHQ_ID__c
      t.text :NOTOR_Flag__c
      t.text :DPIC_Internal_Notes__c
      t.text :Confirmed_Timeslot__c
      t.text :State_Of_Incident__c
      t.text :HasSelfServiceComments
      t.text :Techline_Template__c
      t.text :CA_Reports__c
      t.text :Email_Verbatim__c
      t.text :Field_Close_Date__c
      t.text :Solution_Description__c
      t.text :Airbag_Indicator__c
      t.text :Customer_Satisfied_With_Brand__c
      t.text :Component_Code_Category__c
      t.text :ITA_Subscription_Status__c
      t.text :Parts_Available_Indicator__c
      t.text :Lead_Date__c
      t.text :Dealer_Could_Benefit_By__c
      t.text :Service_Call_ID__c
      t.text :Survey_Verbatim__c
      t.text :Model2__c
      t.text :BusinessHoursId
      t.text :Order_Number_4__c
      t.text :Model_Code__c
      t.text :Risk__c
      t.text :IsVisibleInSelfService
      t.text :Injury_Indicator__c
      t.text :Dealer_Number__c
      t.text :Survey_NPS_Type_3__c
      t.text :Model_Name__c
      t.text :MilestoneStatus
      t.text :Current_Vehicle_Data__c
      t.text :Date_Opened__c
      t.text :Trim_Code__c
      t.text :C_A_R_File__c
      t.text :What_action_was_taken__c
      t.text :Dealer_Forward_Indicator__c
      t.text :Social_Resolved_Time__c
      t.text :Vehicle_Make__c
      t.text :Heads_Up_Date__c
      t.text :WCC_Dealer_Handling_Instructions__c
      t.text :Resolution_Notes__c
      t.text :Backorder_Ranking_2__c
      t.text :Survey_Verbatim_1__c
      t.text :Model_Series__c
      t.text :Vehicle_Name__c
      t.text :ModelIDFromVehicle__c
      t.text :Shipped_Date__c
      t.text :Payment_Offer_Average__c
      t.text :CaseServicingDealerPortal__c
      t.text :Assigned_to__c
      t.text :VehiclesOwned__c
      t.text :Vehicle_Year__c
      t.text :Sent_to_Legal_Date__c
      t.text :Escalated_Type_ID__c
      t.text :Initial_Recommendation__c
      t.text :Origin
      t.text :Spam_Remove_from_Backfeed__c
      t.text :Beyond_PT_Warranty_Miles__c
      t.text :Correction_Notes_Text__c
      t.text :Incident_Category_Code__c
      t.text :Reopen_Other_Count__c
      t.text :CaseNumber
      t.text :Thoroughness_of_Work__c
      t.text :Error_Code__c
      t.text :is1__Mail_ID__c
      t.text :Task_Created_Date__c
      t.text :VSC_Mailing_Zip__c
      t.text :Disqualified__c
      t.text :Call_Recording_ID__c
    end
  end
end
